/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import dao.*;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.*;
/**
 *
 * @author Lenovo
 */
public final class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private final BookDao bd = new BookDao();
    private final StudentDao sd = new StudentDao();
    private final IssueBookDao ibd = new IssueBookDao();
    private final DefaulterDao dd = new DefaulterDao();
    private DefaultTableModel d;
    
    public Home() {
        initComponents();
        numberOfBook();
        numberOfStudent();
        numberOfIssue();
        numberOfList();
        loadBook();
        loadStudent();
    }

    

        
        
        
        
    
    public void numberOfBook() {
        String count = String.valueOf(bd.getNumberOfBook());
        numOfBook.setText(count);
    }
    public void numberOfStudent() {
        String count = String.valueOf(sd.getNumberOfStudent());
        numOfStudent.setText(count);
    }
    public void numberOfIssue() {
        String count = String.valueOf(ibd.getNumberOfIssueBook());
        numOfIssue.setText(count);
    }
    public void numberOfList() {
        String count = String.valueOf(dd.getNumberOfDefaulter());
        numOfList.setText(count);
    }
    public void loadBook() {
        
        List <Books> list = bd.getAllBooks();
        d = (DefaultTableModel) bookTable.getModel();
        d.setRowCount(0);
        
        for (Books b : list) {
            Vector v = new Vector();
            v.add(b.getISBN());
            v.add(b.getName());
            v.add(b.getAuthor());
            v.add(b.getQuantity());
            d.addRow(v);
        }
        
    }
    public void loadStudent() {
        
        List <Students> list = sd.getAllStudents();
        d = (DefaultTableModel) studentTable.getModel();
        d.setRowCount(0);
        
        for (Students s : list) {
            Vector v = new Vector();
            v.add(s.getId());
            v.add(s.getName());
            v.add(s.getUniversity());
            d.addRow(v);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        manageBook = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        manageStudents = new javax.swing.JLabel();
        issueBooklabel = new javax.swing.JPanel();
        issueBooklLabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        returnBook = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        viewRecords = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        viewIssuedBooks = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        defaultList = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        numOfStudent = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        numOfIssue = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        numOfList = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentTable = new rojeru_san.complementos.RSTableMetro();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bookTable = new rojeru_san.complementos.RSTableMetro();
        jLabel34 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        numOfBook = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 5, 50));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Library Management System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel4.setText("Welcome, Admin");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Features");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 340, 60));

        jPanel5.setBackground(new java.awt.Color(255, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel6.setText("   Home Page");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 150, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 60));

        logoutLabel.setBackground(new java.awt.Color(0, 102, 102));
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });
        logoutLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(242, 242, 242));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Exit_26px_1.png"))); // NOI18N
        logout.setText("Logout");
        logoutLabel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        jPanel3.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 340, 60));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        jLabel8.setText("LMS Dashboard");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 340, 60));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageBook.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        manageBook.setForeground(new java.awt.Color(242, 242, 242));
        manageBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Book_26px.png"))); // NOI18N
        manageBook.setText("Manage Books");
        jPanel8.add(manageBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 340, 60));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageStudents.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        manageStudents.setForeground(new java.awt.Color(242, 242, 242));
        manageStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        manageStudents.setText("Manage Students");
        jPanel9.add(manageStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 340, 60));

        issueBooklabel.setBackground(new java.awt.Color(51, 51, 51));
        issueBooklabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issueBooklabelMouseClicked(evt);
            }
        });
        issueBooklabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        issueBooklLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        issueBooklLabel.setForeground(new java.awt.Color(242, 242, 242));
        issueBooklLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        issueBooklLabel.setText("Issue Book");
        issueBooklLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issueBooklLabelMouseClicked(evt);
            }
        });
        issueBooklabel.add(issueBooklLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        jPanel3.add(issueBooklabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 340, 60));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnBook.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        returnBook.setForeground(new java.awt.Color(242, 242, 242));
        returnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        returnBook.setText("Return Book");
        jPanel11.add(returnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 340, 60));

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewRecords.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        viewRecords.setForeground(new java.awt.Color(242, 242, 242));
        viewRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        viewRecords.setText("View Records");
        jPanel12.add(viewRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 340, 60));

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewIssuedBooks.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        viewIssuedBooks.setForeground(new java.awt.Color(242, 242, 242));
        viewIssuedBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Books_26px.png"))); // NOI18N
        viewIssuedBooks.setText("View Issued Books");
        jPanel13.add(viewIssuedBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 340, 60));

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        defaultList.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        defaultList.setForeground(new java.awt.Color(242, 242, 242));
        defaultList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        defaultList.setText("Default List");
        jPanel14.add(defaultList, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 340, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 340, 730));

        jPanel18.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI Historic", 0, 50)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Sell_50px.png"))); // NOI18N
        jLabel20.setText("10");
        jPanel18.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 130, 60));

        jLabel21.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Issued Books");

        jPanel19.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(0, 102, 102)));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI Historic", 0, 50)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        jLabel22.setText("10");
        jPanel19.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 130, 60));

        jLabel23.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Default List");

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(0, 102, 102)));
        jPanel22.setPreferredSize(new java.awt.Dimension(160, 90));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numOfStudent.setFont(new java.awt.Font("Segoe UI Historic", 0, 50)); // NOI18N
        numOfStudent.setForeground(new java.awt.Color(102, 102, 102));
        numOfStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_People_50px.png"))); // NOI18N
        numOfStudent.setText("10");
        jPanel22.add(numOfStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 60));

        jPanel20.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 46, 180, 120));

        jLabel28.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Number Of Students");
        jPanel20.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 6, -1, -1));

        jPanel23.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numOfIssue.setFont(new java.awt.Font("Segoe UI Historic", 0, 50)); // NOI18N
        numOfIssue.setForeground(new java.awt.Color(102, 102, 102));
        numOfIssue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Sell_50px.png"))); // NOI18N
        numOfIssue.setText("10");
        jPanel23.add(numOfIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 60));

        jPanel20.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 46, 180, 120));

        jLabel30.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Issued Books");
        jPanel20.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 6, -1, -1));

        jPanel24.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(0, 102, 102)));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numOfList.setFont(new java.awt.Font("Segoe UI Historic", 0, 50)); // NOI18N
        numOfList.setForeground(new java.awt.Color(102, 102, 102));
        numOfList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        numOfList.setText("10");
        jPanel24.add(numOfList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 60));

        jPanel20.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 46, 180, 120));

        jLabel32.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("Default List");
        jPanel20.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 6, -1, -1));

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Name", "University"
            }
        ));
        studentTable.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
        studentTable.setColorBordeFilas(new java.awt.Color(0, 102, 102));
        studentTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        studentTable.setColorFilasForeground1(new java.awt.Color(0, 102, 102));
        studentTable.setRowHeight(40);
        jScrollPane2.setViewportView(studentTable);

        jPanel20.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 677, 215));

        jLabel33.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Number Of Books");
        jPanel20.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, -1, -1));

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN", "Name", "Author", "Quantity"
            }
        ));
        bookTable.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
        bookTable.setColorBordeFilas(new java.awt.Color(0, 102, 102));
        bookTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        bookTable.setColorFilasForeground1(new java.awt.Color(0, 102, 102));
        bookTable.setRowHeight(40);
        jScrollPane3.setViewportView(bookTable);

        jPanel20.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 640, 210));

        jLabel34.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Book Details");
        jPanel20.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel20.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 206, -1, -1));

        jPanel26.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numOfBook.setFont(new java.awt.Font("Segoe UI Historic", 0, 50)); // NOI18N
        numOfBook.setForeground(new java.awt.Color(102, 102, 102));
        numOfBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Sell_50px.png"))); // NOI18N
        numOfBook.setText("10");
        jPanel26.add(numOfBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 60));

        jLabel26.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Student Details");
        jPanel26.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 28));

        jPanel20.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 46, 180, 120));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(583, 583, 583)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23))
                        .addGap(1227, 1227, 1227))))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 1330, 960));

        setSize(new java.awt.Dimension(1301, 702));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void issueBooklLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBooklLabelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_issueBooklLabelMouseClicked

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void issueBooklabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBooklabelMouseClicked
        // TODO add your handling code here:
        issueBook ib = new issueBook();
        ib.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_issueBooklabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home home  = new Home();
                home.setVisible(true);
                home.setDefaultCloseOperation(EXIT_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSTableMetro bookTable;
    private javax.swing.JLabel defaultList;
    private javax.swing.JLabel issueBooklLabel;
    private javax.swing.JPanel issueBooklabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel logoutLabel;
    private javax.swing.JLabel manageBook;
    private javax.swing.JLabel manageStudents;
    private javax.swing.JLabel numOfBook;
    private javax.swing.JLabel numOfIssue;
    private javax.swing.JLabel numOfList;
    private javax.swing.JLabel numOfStudent;
    private javax.swing.JLabel returnBook;
    private rojeru_san.complementos.RSTableMetro studentTable;
    private javax.swing.JLabel viewIssuedBooks;
    private javax.swing.JLabel viewRecords;
    // End of variables declaration//GEN-END:variables
}
